config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :movies
  resources :casts
  resources :genres

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor_movie.rb
class ActorMovie < ApplicationRecord
    belongs_to :cast
    belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast.rb
class Cast < ApplicationRecord
    
	
	validates :name, :date_of_birth, :no_of_movies, :rank, presence: true
	
	has_many :director_movies
	has_many :actor_movies

	has_many :movies_directed, through: :director_movies, source: :cast
	has_many :movies_acted, through: :actor_movies, source: :cast



end

app/models/director_movie.rb
class DirectorMovie < ApplicationRecord
    belongs_to :cast
    belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

  has_many :genre_movies

  has_many :movies_belong_to_genre, through: :genre_movies, source: :genre
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
    

	validates :name, :ratings, :release_date, :rank, presence:true

	has_many :director_movies
	has_many :actor_movies
	has_many :genre_movies

	has_many :directors, through: :director_movies, source: :movie
	has_many :actors, through: :actor_movies, source: :movie
	has_many :genres, through: :genre_movies, source: :movie

	def update_actors(new_actor_ids)
		#puts new_actor_ids
		existing_actor_ids = actor_movies.pluck(:cast_id)
		actor_ids_to_delete = existing_actor_ids - new_actor_ids
		actor_ids_to_add = new_actor_ids - existing_actor_ids
		actor_movies.where(cast_id: actor_ids_to_delete).delete_all
		new_actor_ids.each do |actor_id_to_add|
			actor_movies.create! cast_id:actor_id_to_add
		end
	end

	def update_genres(new_genre_ids)
		existing_genre_ids = genre_movies.pluck(:genre_id)
		genre_ids_to_delete = existing_genre_ids - new_genre_ids
		genre_ids_to_add = new_genre_ids - existing_genre_ids
		genre_movies.where(genre_id: genre_ids_to_delete).delete_all
		new_genre_ids.each do |genre_id_to_add|
			genre_movies.create! genre_id:genre_id_to_add
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
    before_action :set_cast, only:[:show, :edit, :update, :destroy]
	

	def index
		@casts = Cast.all	
	end

	def new
		@cast = Cast.new
		@movies = Movie.all
	end

	def create
		@cast = Cast.new(cast_params)
        if @cast.save
            @cast.update_movies(params[:movie_ids])
            redirect_to @cast
        else
            render 'new'
        end
  end

	def show
		@cast = Cast.find(params[:id])
		@movies_acted = @cast.movies_acted
		@movies_directed = @cast.movies_directed
	end

	def edit
		@cast = Cast.find(params[:id])
		@movies = Movie.all
	end
	
	def update
		@cast = Cast.find(params[:id])
  	redirect_to @cast
	end

  def destroy
    @cast.destroy
      respond_to do |format|
      format.html { redirect_to casts_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	private

    def set_cast
    	@cast = Cast.find(params[:id])
    end

    def cast_params
    	params.require(:cast).permit(:name, :date_of_birth, :no_of_movies, :rank, :movie_ids)
	end	
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index 
      @genres = Genre.all 
  end

  def new
      @genre = Genre.new
  end

  def create
      @genre = Genre.create(genre_params)
      redirect_to @genre
  end

  def show
      @genre = Genre.find(params[:id])
      @movies_belong_to_genre = @genre.movies_belong_to_genre
  end
  
  def edit
      @genre = Genre.find(params[:id])
      redirect_to @genre
  end

  def update
      @genre = Genre.find(params[:id])
      redirect_to @genre
  end

  def destroy
      @genre = Genre.find(params[:id])
      @genre.destroy

      redirect_to genres_path
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, :movie_ids)
  end	


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    before_action :set_movie, only: [:show, :edit, :update, :destroy]

    def index 
        @movies = Movie.all 
    end

    def new
        @movie = Movie.new
        @casts = Cast.all
        @genres = Genre.all
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            @movie.update_actors(params[:actor_ids])
            redirect_to @movie
        else
            render 'new'
        end
    end

    def show
        @movie = Movie.find(params[:id])
    end
    
    def edit
        @movie = Movie.find(params[:id])
        @casts = Cast.all
        @genres = Genre.all
    end

    def update
        @movie = Movie.find(params[:id])
        
        if @movie.update(movie_params)
            @movie.update_actors(params[:actor_ids])
            @movie.update_genres(params[:genre_ids])
            redirect_to @movie
        else
            render 'edit'
        end
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy

        redirect_to movies_path
    end

    private

    def set_movie
    	@movie = Movie.find(params[:id])
    end

    def movie_params
    	params.require(:movie).permit(:name, :ratings, :release_date, :rank, :actor_ids, :genre_ids)
    end	

    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/casts/_form.html.erb
<%= form_with model: @cast, local: true do |form| %>
 
    <% if @cast.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@cast.errors.count, "error") %> prohibited
          this cast from being saved:
        </h2>
        <ul>
          <% @cast.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
   
    <p>
      <%= form.label :date_of_birth %><br>
      <%= form.text_field :date_of_birth %>
    </p>

    <p>
      <%= form.label :no_of_movies %><br>
      <%= form.text_field :no_of_movies %>
    </p>
   
    <p>
      <%= form.label :rank %><br>
      <%= form.text_field :rank %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/casts/edit.html.erb
<h1>Editing Casts</h1>

<%= render 'form' %>

<%= link_to 'Show', @cast %> |
<%= link_to 'Back', casts_path %>

app/views/casts/index.html.erb
<h1>Listing Casts</h1>

<table>
  <thead>
    <tr>
      <th>Cast Name</th>
      <th>"Date of Birth"</th>
      <th>"Number of Films"</th>
      <th>Rank</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casts.each do |cast| %>
      <tr>
        <td><%= cast.name%></td>
        <td><%= cast.date_of_birth%></td>
        <td><%= cast.no_of_movies%></td>
        <td><%= cast.rank%></td>

        <td><%= link_to 'Show', cast %></td>
        <td><%= link_to 'Edit', edit_cast_path(cast) %></td>
        <td><%= link_to 'Destroy', cast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Casts', new_cast_path %><br/>
<%= link_to 'Back', welcome_index_path%>

app/views/casts/new.html.erb
<h1>New Cast</h1>

<%= render 'form' %>

<%= link_to 'Back', casts_path %>

app/views/casts/show.html.erb
Name: <%= @cast.name %><br/>
Date of Birth: <%= @cast.date_of_birth %><br/>
Number of Movies: <%= @cast.no_of_movies %><br/>
Rank : <%= @cast.rank %><br/>

<br>

<h2>Movies Acted</h2>
<% @cast.actor_movies.pluck(:movie_id).each do |id| %>
	<%= link_to Movie.find(id).name, Movie.find(id) %>
	<br>
<% end %>
<br>

<h2>Movies Directed</h2>
<% @cast.director_movies.pluck(:movie_id).each do |id| %>
	<%= link_to Movie.find(id).name, Movie.find(id) %>
	<br>
<% end %>
<br>


<%= link_to 'Edit', edit_cast_path(@cast)  %>
<%= link_to 'Back', casts_path %>
<%= link_to "Edit", edit_cast_path(@cast) %>


<br>
<br>

app/views/genres/_form.html.erb
<%= form_with model: @genre, local: true do |form| %>
 
  <% if @genre.errors.any? %>
   <div id="error_explanation">
    <h2>
     <%= pluralize(@genre.errors.count, "error") %> prohibited
     this genre from being saved:
    </h2>
    <ul>
     <% @genre.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
    </ul>
   </div>
  <% end %>
  
  <p>
   <%= form.label :name %><br>
   <%= form.text_field :name %>
  </p>

  <p>
   <%= form.submit %>
  </p>
  
 <% end %>

app/views/genres/edit.html.erb
<h1>Editing Genres</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing Genres</h1>

<table>
  <thead>
    <tr>
      <th>Genre Name   :</th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
Name: <%= @genre.name %><br/>

<p>
	<strong> Movies </strong>
	<% @genre.genre_movies.pluck(:movie_id).each do |id| %>
	<%= link_to Movie.find(id).name, Movie.find(id) %>
	
	<% end %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre)  %>
<%= link_to 'Back', genres_path %>


<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMDB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: @movie, local: true do |form| %>
 
  <% if @movie.errors.any? %>
   <div id="error_explanation">
    <h2>
     <%= pluralize(@movie.errors.count, "error") %> prohibited
     this movie from being saved:
    </h2>
    <ul>
     <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
    </ul>
   </div>
  <% end %>
  
  <p>
   <%= form.label :name %><br>
   <%= form.text_field :name %>
  </p>
  
  <p>
   <%= form.label :ratings %><br>
   <%= form.text_field :ratings %><br>
  </p>

  <p>
   <%= form.label :release_date %><br>
   <%= form.text_field :release_date %>
  </p>

  <p>
  <table>
    <%= form.label :Genres %><br>
      <% @genres.each do |genre| %>
       <tr><td>
       <input type = "checkbox" value = <%= genre.id %> name = "genre_ids[]" >
       <label for = "genre_ids[]" > <%= genre.name %> </label>
       </td></tr>
    <% end %>
  </table>

  </p>

  <p>
  <table>
    <%= form.label :Actors %><br>
      <% @casts.each do |cast| %>
       <tr><td>
       <input type = "checkbox" value = <%= cast.id %> name = "actor_ids[]" >
       <label for = "actor_ids[]" > <%= cast.name %> </label>
       </td></tr>
    <% end %>
  </table>

  </p>
  
<p>
  <table>
    <%= form.label :Directors %><br>
      <% @casts.each do |cast| %>
       <tr><td>
       <input type = "checkbox" value = <%= cast.id %> name = "director_ids[]" >
       <label for = "director_ids[]" > <%= cast.name %> </label>
       </td></tr>
    <% end %>
  </table>

</p>

  <p>
   <%= form.label :rank %><br>
   <%= form.text_field :rank %>
  </p>
  
  <p>
   <%= form.submit %>
  </p>
  
 <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Movie Name   :</th>
      <th>Ratings      :</th>
      <th>Release Date :</th>
      <th>Rank         :</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.ratings%></td>
        <td><%= movie.release_date%></td>
        <td><%= movie.rank%></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
  
</table>


<br>

<%= link_to 'New Movies', new_movie_path %><br>
<%= link_to 'Back', welcome_index_path%>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
Name: <%= @movie.name %><br/>
Ratings: <%= @movie.ratings %><br/>
Release Date: <%= @movie.release_date %><br/>
Rank  : <%= @movie.rank%><br/>


<p>
	<strong> Actors </strong>
	<% @movie.actor_movies.pluck(:cast_id).each do |id| %>
	<%= link_to Cast.find(id).name, Cast.find(id) %>
	
	<% end %>
</p>

<p>
	<strong> Directors </strong>
	<% @movie.director_movies.pluck(:cast_id).each do |id| %>
	<%= link_to Cast.find(id).name, Cast.find(id) %>
	
	<% end %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie)  %>
<%= link_to 'Back', movies_path %>


<br>
<br>

app/views/welcome/index.html.erb
<h1> Welcome to IMDB </h1>

<%= link_to 'Top 10 Movies', controller: 'movies' %>
<%= link_to 'Top 10 Casts', controller: 'casts' %>